# Generated by Django 6.0 on 2026-01-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_address_booking_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wedding_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
