# Generated by Django 6.0 on 2026-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_concertbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertbooking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
