# Generated by Django 6.0 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_concertbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertbooking',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='concertbooking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
