# Generated by Django 6.0 on 2026-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tournament_sportsregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
