# Generated by Django 6.0 on 2026-01-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='round_number',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
