# Generated by Django 6.0 on 2026-01-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_fixture_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_p1', to='main.sportsregistration'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_p2', to='main.sportsregistration'),
        ),
    ]
