# Generated by Django 6.0 on 2026-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_fixture_player1_alter_fixture_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
