# Generated by Django 6.0 on 2026-01-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(default='Team', max_length=50),
        ),
    ]
