# Generated by Django 6.0 on 2026-01-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsregistration',
            name='winning_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
