# Generated by Django 6.0 on 2026-01-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_blog_is_deleted_booking_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artistBio', models.TextField()),
                ('popularTracks', models.JSONField(blank=True, default=list)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('bannerImage', models.TextField()),
                ('thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=dict)),
                ('tickets', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('sponsors', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('color', models.CharField(default='rgba(0,0,0,0.9)', max_length=100)),
                ('secondary', models.CharField(default='#FFD700', max_length=50)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('about', models.TextField()),
                ('attractions', models.JSONField(blank=True, default=list)),
                ('passes', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
