# Generated by Django 6.0 on 2026-01-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_concert_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='booking_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='booking_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
